### ISSUE TITLE
Null displayed as first name of the user in the import feedback, even if the user is imported properly

### ISSUE THREAD

**Issue by lucaa** [xwikisas/application-ldapuserimport#35]
Reproduced on version 1.0.3 of the ldap user import.

Upon import of a user, in the confirmation message, "null" is displayed as the first name of the user instead of their actual first name: 

![image](https://user-images.githubusercontent.com/657716/120302328-15d0f780-c2ce-11eb-94ad-842d43579c04.png)

even if, in the created user profile, the first name of the user is properly filled in.

In the ldap configuration, the first name is mapped to the ldap field ```givenname``` .

Note: on a search of users, in the search results, this user is properly displayed with their first name.

**Comment by lucaa** [comment]
@acotiuga please check that there is no (leftover or intentional) hardcoding of the fields used to fetch this information. 
Another suspect may be the case of the ldap field (I notice ```givenname``` field when usually it's more like ```givenName```), but these are just shots in the dark, proper investigation will probably contradict me.

**Comment by acotiuga** [comment]
The problem was that the translations were using a fix list of parameters, corresponding to LDAP attributes,  and some of them could be missing if there is no data in LDAP. In order to fix this, a solution is to concatenate the values of the existing attributes and provide a single parameter to translation. 

Also, an improvement was implemented to provide some minimal data (first_name, last_name, email, username) even if the LDAP configuration provides a partial mapping (e.g.: only mapping the first_name), in which case the data from the other fields would not be displayed in the search/import feedback list.
